name: Run Python Files

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-python-files:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Specify the Python version you need

      # Step 3: Install dependencies (if needed)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_trainingModels.txt  # Install dependencies from requirements.txt
          pip install -e .  # Install the package in editable mode

      # Step 4: Run Python files
      - name: Run /src/data/import_raw_data.py
        run: python ${{ github.workspace }}/src/data/import_raw_data.py  # Replace with the path to your first Python file

      - name: Run /src/data/make_dataset.py
        run: python ${{ github.workspace }}/src/data/make_dataset.py  # Replace with the path to your first Python file

      - name: Run /src/models/train_model.py
        run: python ${{ github.workspace }}/src/models/train_model.py  # Replace with the path to your first Python filegit 